// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2nd.Semester.Eksamen.Infrastructure.Data;

#nullable disable

namespace _2nd.Semester.Eksamen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251119083316_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PointBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customer");

                    b.HasDiscriminator().HasValue("Customer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Appointments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BasePriceMultiplier")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ExperienceLevel")
                        .HasColumnType("int");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedDiscountId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DiscountedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Products")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppliedDiscountId");

                    b.HasIndex("BookingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("Employee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductsUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TreatmentID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("TreatmentID");

                    b.ToTable("BookedTreatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TreatmentSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Customer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CustomerID")
                        .HasColumnType("int");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.ProductSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberSold")
                        .HasColumnType("int");

                    b.Property<decimal?>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentId");

                    b.ToTable("ProductSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.Property<bool>("Product")
                        .HasColumnType("bit");

                    b.Property<bool>("Treatment")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.HasDiscriminator().HasValue("Discount");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.PunchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FreeTreatments")
                        .HasColumnType("int");

                    b.Property<int>("PunchNumber")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.CompanyCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer");

                    b.Property<string>("CVRNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CompanyCustomer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.PrivateCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PrivateCustomer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Treatment", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Product");

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.HasIndex("CampaignId");

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("End")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("ProductCategories")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Start")
                        .HasColumnType("datetime2");

                    b.HasDiscriminator().HasValue("Campaign");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.LoyaltyDiscount", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount");

                    b.Property<string>("DiscountType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MinimumVisits")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("LoyaltyDiscount");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", "AppliedDiscount")
                        .WithMany()
                        .HasForeignKey("AppliedDiscountId");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.Navigation("AppliedDiscount");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Booking", "Booking")
                        .WithMany("Treatments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentSnapshot", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Booking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", null)
                        .WithMany("BookingHistory")
                        .HasForeignKey("CustomerID");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", null)
                        .WithMany("TreatmentHistory")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.ProductSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Treatment", null)
                        .WithMany("Products")
                        .HasForeignKey("TreatmentId");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.PunchCard", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", "Customer")
                        .WithMany("PunchCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Treatment", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", null)
                        .WithMany("Treatments")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.Navigation("BookingHistory");

                    b.Navigation("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.Navigation("TreatmentHistory");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Booking", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Produkter.Treatment", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", b =>
                {
                    b.Navigation("Treatments");
                });
#pragma warning restore 612, 618
        }
    }
}
