// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2nd.Semester.Eksamen.Infrastructure.Data;

#nullable disable

namespace _2nd.Semester.Eksamen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260105032546_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppliesToProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("AppliesToTreatment")
                        .HasColumnType("bit");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsLoyalty")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.Property<decimal>("ProductDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TreatmentDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Discount", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.PunchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FreeTreatments")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PunchNumber")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.AddressSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.AppliedDiscountSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProductDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TreatmentDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AppliedDiscountSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerSnapshotId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerSnapshotId")
                        .IsUnique();

                    b.ToTable("BookingsSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressSnapshotId")
                        .IsUnique()
                        .HasFilter("[AddressSnapshotId] IS NOT NULL");

                    b.ToTable("CustomerSnapshots");

                    b.HasDiscriminator().HasValue("CustomerSnapshot");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.EmployeeSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BasePriceMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.OrderLineSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<int?>("OrderSnapshotId")
                        .HasColumnType("int");

                    b.Property<int>("ProductSnapshotId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderSnapshotId");

                    b.HasIndex("ProductSnapshotId");

                    b.ToTable("OrderLinesSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AppliedSnapshotId")
                        .HasColumnType("int");

                    b.Property<int?>("BookingSnapshotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CustomDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly>("DateOfPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("date");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("PdfInvoice")
                        .HasColumnType("varbinary(max)");

                    b.Property<decimal?>("TotalAfterDiscount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppliedSnapshotId")
                        .IsUnique()
                        .HasFilter("[AppliedSnapshotId] IS NOT NULL");

                    b.HasIndex("BookingSnapshotId")
                        .IsUnique()
                        .HasFilter("[BookingSnapshotId] IS NOT NULL");

                    b.ToTable("OrderSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.ProductSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("DiscountedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PricePerUnit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("ProductSnapshots");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfVisists")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PointBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SaveAsCustomer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customers");

                    b.HasDiscriminator().HasValue("Customer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePriceMultiplier")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialties")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly>("WorkEnd")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("WorkStart")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<DateTime>("End")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Start")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("BookedTreatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBookingProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentBookingID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("TreatmentBookingID");

                    b.ToTable("TreatmentBookingProducts");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedDiscountId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VAT")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderID");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountedPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.ScheduleDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ScheduleDays");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.TimeRange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("ActivityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("End")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<Guid>("Guid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduleDayId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("Start")
                        .HasPrecision(0)
                        .HasColumnType("time(0)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("ScheduleDayId");

                    b.ToTable("TimeRanges");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Campaign", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Discount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.LoyaltyDiscount", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Discount");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumVisits")
                        .HasColumnType("int");

                    b.ToTable("LoyaltyDiscounts", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.CompanyCustomerSnapshot", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot");

                    b.Property<string>("CVR")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CompanyCustomerSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.PrivateCustomerSnapshot", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PrivateCustomerSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.TreatmentSnapshot", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.History.ProductSnapshot");

                    b.Property<int>("BookingSnapshotId")
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("EmployeeGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmployeeSnapshotId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceWithMultiplier")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("TreatmentBookingGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("BookingSnapshotId");

                    b.HasIndex("EmployeeSnapshotId");

                    b.ToTable("TreatmentSnapshots");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.CompanyCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer");

                    b.Property<string>("CVRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("CompanyCustomer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.PrivateCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("PrivateCustomer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.Treatment", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Products.Product");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.PrimitiveCollection<string>("RequiredSpecialties")
                        .HasColumnType("nvarchar(max)");

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.PunchCard", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer", "Customer")
                        .WithMany("PunchCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot", "CustomerSnapshot")
                        .WithOne("BookingSnapshot")
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", "CustomerSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CustomerSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.AddressSnapshot", "AddressSnapshot")
                        .WithOne("CustomerSnapshot")
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot", "AddressSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AddressSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.OrderLineSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", "OrderSnapshot")
                        .WithMany("OrderLinesSnapshot")
                        .HasForeignKey("OrderSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.ProductSnapshot", "ProductSnapshot")
                        .WithMany("OrderLines")
                        .HasForeignKey("ProductSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderSnapshot");

                    b.Navigation("ProductSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.AppliedDiscountSnapshot", "AppliedDiscountSnapshot")
                        .WithOne("OrderSnapshot")
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", "AppliedSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", "BookingSnapshot")
                        .WithOne("OrderSnapshot")
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", "BookingSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppliedDiscountSnapshot");

                    b.Navigation("BookingSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer", "Customer")
                        .WithMany("BookingHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBooking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", "Booking")
                        .WithMany("Treatments")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Employee");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBookingProduct", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBooking", "TreatmentBooking")
                        .WithMany("TreatmentBookingProducts")
                        .HasForeignKey("TreatmentBookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("TreatmentBooking");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", "Booking")
                        .WithOne("Order")
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", "BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.OrderLine", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", "LineProduct")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LineProduct");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Campaign", null)
                        .WithMany("ProductsInCampaign")
                        .HasForeignKey("CampaignId");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.ScheduleDay", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", "Employee")
                        .WithMany("Schedule")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.TimeRange", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.ScheduleDay", "ScheduleDay")
                        .WithMany("TimeRanges")
                        .HasForeignKey("ScheduleDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("ScheduleDay");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Campaign", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Discount", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Campaign", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.LoyaltyDiscount", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Discount", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Discounts.LoyaltyDiscount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.TreatmentSnapshot", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", "BookingSnapshot")
                        .WithMany("TreatmentSnapshot")
                        .HasForeignKey("BookingSnapshotId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.EmployeeSnapshot", "EmployeeSnapshot")
                        .WithMany()
                        .HasForeignKey("EmployeeSnapshotId");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.History.ProductSnapshot", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.History.TreatmentSnapshot", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BookingSnapshot");

                    b.Navigation("EmployeeSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.AddressSnapshot", b =>
                {
                    b.Navigation("CustomerSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.AppliedDiscountSnapshot", b =>
                {
                    b.Navigation("OrderSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.BookingSnapshot", b =>
                {
                    b.Navigation("OrderSnapshot")
                        .IsRequired();

                    b.Navigation("TreatmentSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.CustomerSnapshot", b =>
                {
                    b.Navigation("BookingSnapshot")
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.OrderSnapshot", b =>
                {
                    b.Navigation("OrderLinesSnapshot");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.History.ProductSnapshot", b =>
                {
                    b.Navigation("OrderLines");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer.Customer", b =>
                {
                    b.Navigation("BookingHistory");

                    b.Navigation("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employees.Employee", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.Booking", b =>
                {
                    b.Navigation("Order")
                        .IsRequired();

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.BookingProducts.TreatmentProducts.TreatmentBooking", b =>
                {
                    b.Navigation("TreatmentBookingProducts");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Schedules.EmployeeSchedules.ScheduleDay", b =>
                {
                    b.Navigation("TimeRanges");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Discounts.Campaign", b =>
                {
                    b.Navigation("ProductsInCampaign");
                });
#pragma warning restore 612, 618
        }
    }
}
