// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2nd.Semester.Eksamen.Infrastructure.Data;

#nullable disable

namespace _2nd.Semester.Eksamen.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfVisists")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PointBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("SaveAsCustomer")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Customer");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<decimal>("BasePriceMultiplier")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppliedDiscountId")
                        .HasColumnType("int");

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountedTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AppliedDiscountId");

                    b.HasIndex("BookingId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.OrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LineProductId")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfProducts")
                        .HasColumnType("int");

                    b.Property<int>("OrderID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LineProductId");

                    b.HasIndex("OrderID");

                    b.ToTable("OrderLine");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CampaignId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TreatmentBookingId")
                        .HasColumnType("int");

                    b.Property<int?>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CampaignId");

                    b.HasIndex("TreatmentBookingId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("Products");

                    b.HasDiscriminator().HasValue("Product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingID")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingID");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("BookedTreatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AppliesToProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("AppliesToTreatment")
                        .HasColumnType("bit");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfUses")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Discount");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.PunchCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("FreeTreatments")
                        .HasColumnType("int");

                    b.Property<int>("PunchNumber")
                        .HasColumnType("int");

                    b.Property<int>("TreatmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("TreatmentId");

                    b.ToTable("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.CompanyCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer");

                    b.Property<string>("CVRNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("CompanyCustomers", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.PrivateCustomer", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PrivateCustomers", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Treatment", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Products.Product");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.HasDiscriminator().HasValue("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.ToTable("Campaigns", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.LoyaltyDiscount", b =>
                {
                    b.HasBaseType("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MinimumVisits")
                        .HasColumnType("int");

                    b.ToTable("LoyaltyDiscounts", (string)null);
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Address", "Address")
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", "AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Booking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", "Customer")
                        .WithMany("BookingHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", null)
                        .WithMany("TreatmentHistory")
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", "AppliedDiscount")
                        .WithMany()
                        .HasForeignKey("AppliedDiscountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppliedDiscount");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.OrderLine", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", "LineProduct")
                        .WithMany()
                        .HasForeignKey("LineProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", "Order")
                        .WithMany("Products")
                        .HasForeignKey("OrderID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LineProduct");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Product", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", null)
                        .WithMany("ProductsInCampaign")
                        .HasForeignKey("CampaignId");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", null)
                        .WithMany("ProductsUsed")
                        .HasForeignKey("TreatmentBookingId");

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Treatment", null)
                        .WithMany("Products")
                        .HasForeignKey("TreatmentId");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Booking", "Booking")
                        .WithMany("Treatments")
                        .HasForeignKey("BookingID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", "Employee")
                        .WithMany("Appointments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Employee");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.PunchCard", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", "Customer")
                        .WithMany("PunchCards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Products.Treatment", "Treatment")
                        .WithMany()
                        .HasForeignKey("TreatmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Treatment");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.CompanyCustomer", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Persons.CompanyCustomer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.PrivateCustomer", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Persons.PrivateCustomer", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.LoyaltyDiscount", b =>
                {
                    b.HasOne("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Discount", null)
                        .WithOne()
                        .HasForeignKey("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.LoyaltyDiscount", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Customer", b =>
                {
                    b.Navigation("BookingHistory");

                    b.Navigation("PunchCards");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Persons.Employee", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("TreatmentHistory");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Booking", b =>
                {
                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Order", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.TreatmentBooking", b =>
                {
                    b.Navigation("ProductsUsed");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Products.Treatment", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_2nd.Semester.Eksamen.Domain.Entities.Tilbud.Campaign", b =>
                {
                    b.Navigation("ProductsInCampaign");
                });
#pragma warning restore 612, 618
        }
    }
}
